env: "local" #local, dev, prod
storage_path: "postgres://postgres:psqlpassword@db:5432/tokens_db?sslmode=disable"
jwt_secret: "your-256-super-strong-jwt-secretbit-secret"
http_server:
  address: "0.0.0.0:9000"
  timeout: 4s
  idle_timeout: 60s